### ISSUE TITLE
Hyprland dual with Plasma

### ISSUE THREAD

**Issue by nandarmath** [aster-void/nixos-config#1]
i want too, dual hyprland and plasma on my nixos, but i dont know to do it,

**Comment by aster-void** [comment]
I don't know about Display Manager either, but I'll try.

**Comment by aster-void** [comment]
Hi. I got it working. It's just `services.displayManager.autoLogin.enable = false` and I can choose which DE/WM to launch from sddm.

(just to inform you, ) There seems to be a slight issue with nvidia graphics driver since middle of May, so Hyprland might not launch on latest unstable. It launches on 2024-05-11 13:59:59 generation, so if yours get stuck in SDDM, try rolling it back to somewhere near that generation.
